// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview A contract improvement suggestion AI agent.
 *
 * - suggestContractImprovements - A function that suggests improvements to a contract.
 * - SuggestContractImprovementsInput - The input type for the suggestContractImprovements function.
 * - SuggestContractImprovementsOutput - The return type for the suggestContractImprovements function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SuggestContractImprovementsInputSchema = z.object({
  contract: z.string().describe('The contract to be improved.'),
  answers: z.record(z.string()).describe('The answers to the questionnaire.'),
});
export type SuggestContractImprovementsInput = z.infer<
  typeof SuggestContractImprovementsInputSchema
>;

const SuggestContractImprovementsOutputSchema = z.object({
  suggestions: z
    .string()
    .describe('Suggestions for improving the contract.'),
});
export type SuggestContractImprovementsOutput = z.infer<
  typeof SuggestContractImprovementsOutputSchema
>;

export async function suggestContractImprovements(
  input: SuggestContractImprovementsInput
): Promise<SuggestContractImprovementsOutput> {
  return suggestContractImprovementsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'suggestContractImprovementsPrompt',
  input: {schema: SuggestContractImprovementsInputSchema},
  output: {schema: SuggestContractImprovementsOutputSchema},
  prompt: `You are an expert legal consultant. You will review the contract provided and suggest improvements to its clarity, completeness, and legal soundness, based on the contract's content and the user's answers to the questionnaire.

Contract:
{{contract}}

Questionnaire Answers:
{{#each answers}}
  {{@key}}: {{this}}
{{/each}}

Suggestions:`,
});

const suggestContractImprovementsFlow = ai.defineFlow(
  {
    name: 'suggestContractImprovementsFlow',
    inputSchema: SuggestContractImprovementsInputSchema,
    outputSchema: SuggestContractImprovementsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
